openapi: 3.0.0
info:
  title: Jsonplace Holder
  description: This is a sample Mock data.
  version: 1.0.0
servers:
- url: https://jsonplaceholder.typicode.com
tags:
- name: posts
  description: Access to Jsonplace posts
paths:
  /posts:
    get:
      tags:
      - posts
      summary: Returns jsonplace posts by status
      description: Returns a jsonplace posts
      operationId: getPosts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                    id:
                      type: integer
                    title:
                      type: string
                    body:
                      type: string
components:
  securitySchemes:
    basicAuth:     
      type: http
      scheme: basic
security:
  - basicAuth: []
